# site settings
title: Muh. Fikri Khaidir
subtitle: Blog & Portfolio
email: fikrikhaidir@gmail.com
description: Project Manager | Python Programmer | Django Web Developer | AI Researcher
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://github.com/fikrikhaidir" # the base hostname & protocol for your site
author: Muh. Fikri Khaidir
street_address: Kaliurang St.
city: Special Region of Yogyakarta
state: Java
zip_code: 55555
country: Indonesia
#phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url: https://github.com/fikrikhaidir/
github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+fikrikhaidir
instagram_url: https://instagram.com/fikrikhaidir/
linkedin_url: https://www.linkedin.com/in/muhammad-fikri-khaidir-98347a118/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/fikrikhaidir

# build settings
markdown: kramdown

sass:
  style: compressed
